[default.extend-words]
# noice.nvim
noice = "noice"
# vim keymap
enew = "enew"
# starship config
edn = "edn"
esy = "esy"
ane = "ane"
nane = "nane"
# macOS Big Sur
sur = "sur"
# fish abbr `chezmoi cd`
chec = "chec"
# key mapping in dot_config/nvim/lua/plugins/telescope-nvim.lua
fo = "fo"
# telescope-nvim
tabe = "tabe"
# dot_config/nvim/lua/plugins/minigames.lua
strat = "strat"
# dot_config/nvim/lua/plugins/colorscheme/themes/lackluster.lua
tweek = "tweek"
# dot_config/gotop/gotop.conf
# error: `Promethius` should be `Prometheus`
Promethius = "Promethius"

[files]
extend-exclude = [
  # NOTE: Experimental software and no fixes are expect
  "dot_config/fish/completions/fish-lsp.fish",
  # NOTE: Game settings
  "game_settings/Apex_Legends",
  "game_settings/CookieClicker",
  # NOTE: Unmaintained and no upstream fixes
  "dot_config/pipr/pipr.toml",
  "dot_config/gotop/gotop.conf",
]
