[default.extend-words]
# noice.nvim
noice = "noice"
# vim keymap
enew = "enew"
# iterm2
iterm = "iterm"
# starship config
edn = "edn"
esy = "esy"
# macOS Big Sur
sur = "sur"
# fish abbr `chezmoi cd`
chec = "chec"
# Linux OS name
Siduction = "Siduction"

[files]
extend-exclude = [
    "pnpm-lock.yaml",
    # Not fixed
    "dot_ghcup/config.yaml",
    # NOTE: Unmaintained and no upstream fixes
    "dot_config/pipr/pipr.toml",
]
