[default.extend-words]
# noice.nvim
noice = "noice"
# vim keymap
enew = "enew"
# iterm2
iterm = "iterm"
# starship config
edn = "edn"
esy = "esy"
ane = "ane"
nane = "nane"
# macOS Big Sur
sur = "sur"
# fish abbr `chezmoi cd`
chec = "chec"
# Linux OS name
Siduction = "Siduction"
# key mapping in dot_config/nvim/lua/plugins/telescope-nvim.lua
fo = "fo"
# telescope-nvim
tabe = "tabe"

[files]
extend-exclude = [
  "pnpm-lock.yaml",
  "game_settings/Apex_Legends",
  "game_settings/CookieClicker",
  # Not fixed
  # PR sent.
  # https://github.com/haskell/ghcup-hs/pull/943
  "dot_ghcup/config.yaml",
  # NOTE: Unmaintained and no upstream fixes
  "dot_config/pipr/pipr.toml",
]
