[tools]
dotnet-core = "latest"
lua = "latest"
luajit = "latest"
tig = "latest"
vim = "9.1.0336"
ruby = "latest"
neovim = "nightly"
node = "20"
powershell-core = "7.4"
python = "3"
zig = "master"

[plugins]
luajit = "https://github.com/smashedtoatoms/asdf-luaJIT.git"
tig = "https://github.com/koketani/asdf-tig.git"
