[tools]
dotnet-core = "latest"
erlang = "latest"
gleam = "latest"
go = "latest"
lua = "5.1.5"
luajit = "2.0.5--2.4.4"
node = "22"
powershell-core = "7.4"
python = "3"
ruby = "latest"
vim = "latest"
zig = "latest"

[plugins]
luajit = "https://github.com/smashedtoatoms/asdf-luaJIT.git"
vim = "https://github.com/mimikun/asdf-vim.git"
