[default.extend-words]
noice = "noice"
enew = "enew"
iterm = "iterm"
edn = "edn"

[files]
extend-exclude = [
    "dot_config/fish/completions",
    "dot_config/starship/starship.toml",
    "dot_config/neofetch/config.conf",
    "dot_ghcup/config.yaml",
    "dot_config/pipr/pipr.toml",
    "private_dot_local/bin/executable_wsl-open",
]
