[tools]
dotnet-core = "latest"
erlang = "latest"
gleam = "latest"
go = "latest"
ruby = "latest"
lua = "5.1"
"asdf:neovim" = [
    "nightly",
    "stable",
    "0.10.4",
    "ref:master",
]
node = [
    "lts",
    "22",
    "latest",
    "23",
]
python = [
    "latest",
    "3",
]
vim = [
    "ref:master",
    "latest",
]
zig = [
    "ref:master",
    "latest",
]

# npm backends
"npm:commitizen" = "latest"
"npm:cz-conventional-changelog-ja" = "latest"
"npm:envinfo" = "latest"
"npm:npkill" = "latest"
"npm:prettier" = "latest"

[settings]
asdf_compat = true
experimental = true
jobs = 1

[settings.cargo]
binstall = false

[settings.npm]
bun = true

[settings.pipx]
uvx = true

[settings.status]
missing_tools = "if_other_versions_installed"
