[tools]
dotnet-core = "latest"
erlang = "latest"
gleam = "latest"
lua = "5.1.5"
luajit = "2.0.5--2.4.4"
node = [
    # lts = 20
    "20",
    "21",
    "22",
]
powershell-core = [
    "latest",
    "7.4",
]
python = [
    "latest",
    # mise cannot install python v2
    #"2",
    "3",
]
ruby = "latest"
tig = "latest"
vim = [
    "latest",
    "ref:master",
]
zig = [
    "ref:master",
    "latest",
]
# npm backends
"npm:npkill" = "latest"

[plugins]
luajit = "https://github.com/smashedtoatoms/asdf-luaJIT.git"
tig = "https://github.com/koketani/asdf-tig.git"
vim = "https://github.com/mimikun/asdf-vim.git"
