[tools]
dotnet-core = "latest"
erlang = "latest"
gleam = "latest"
go = "latest"
lua = "5.1"
node = [
    "lts",
    "22",
    "latest",
    "23",
]
powershell-core = [
    "latest",
    "7.4",
]
python = [
    "latest",
    "3",
]
ruby = "latest"
vim = [
    "ref:master",
    "latest",
]
zig = [
    "ref:master",
    "latest",
]

# npm backends
"npm:commitizen" = "latest"
"npm:cz-conventional-changelog-ja" = "latest"
"npm:envinfo" = "latest"
"npm:npkill" = "latest"
"npm:prettier" = "latest"

[settings]
asdf_compat = true
experimental = true
# FIX: search and configuring
jobs = 4

[settings.cargo]
binstall = false

[settings.npm]
bun = true

[settings.pipx]
uvx = true

[settings.status]
missing_tools = "if_other_versions_installed"
