[dev]
path = "~/ghq/github.com/mimikun/dev-plugins"

[rocks]

[plugins]
"rocks.nvim" = "2.40.4"
"rocks-git.nvim" = "2.5.0"
"rocks-lazy.nvim" = "1.1.1"
"rocks-edit.nvim" = "scm"
"rocks-config.nvim" = "3.0.0"
"rocks-dev.nvim" = "1.7.0"
"rocks-treesitter.nvim" = "1.1.3"

# NOTE: Vim Script Plugins
[plugins.calendar-vim]
git = "mattn/calendar-vim"
cmd = "Calendar"

[plugins."chezmoi.vim"]
git = "alker0/chezmoi.vim"
#------------------------------------------------------------------------------------

[plugins.alpha-nvim]
git = "goolord/alpha-nvim"
#version = "scm"
cmd = "Alpha"
event = "VimEnter"

[plugins.nvim-web-devicons]
#git = "nvim-tree/nvim-web-devicons"
version = "0.100"

[plugins."plenary.nvim"]
#git = "nvim-lua/plenary.nvim"
version = "scm"

[plugins."2048.nvim"]
#git = "NStefan002/2048.nvim"
version = "2.8.2"
cmd = "Play2048"
config = true

[plugins."accelerated-jk.nvim"]
git = "rainbowhxch/accelerated-jk.nvim"
event = "BufRead"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
cmd = [
  "BufferPrevious",
  "BufferNext",
  "BufferMovePrevious",
  "BufferMoveNext",
  "BufferGoto",
  "BufferLast",
  "BufferPin",
  "BufferClose",
  "BufferRestore",
  "BufferWipeout",
  "BufferCloseAllButCurrent",
  "BufferCloseAllButVisible",
  "BufferCloseAllButPinned",
  "BufferCloseAllButCurrentOrPinned",
  "BufferCloseBuffersLeft",
  "BufferCloseBuffersRight",
  "BufferPick",
  "BufferPickDelete",
  "BufferOrderByBufferNumber",
  "BufferOrderByName",
  "BufferOrderByDirectory",
  "BufferOrderByLanguage",
  "BufferOrderByWindowNumber",
  "BarbarEnable",
  "BarbarDisable",
]
event = "BufEnter"

[plugins."gitsigns.nvim"]
#git = "lewis6991/gitsigns.nvim"
version = "0.9.0"

[plugins."buffer-reopen.nvim"]
git = "iamyoki/buffer-reopen.nvim"
cmds = "BufferHistory"

[plugins."ccc.nvim"]
#git = "uga-rosa/ccc.nvim"
version = "1.6.0"
cmd = [
  "CccPick",
  "CccConvert",
  "CccHighlighterEnable",
  "CccHighlighterDisable",
  "CccHighlighterToggle",
]
event = "BufEnter"

# TODO: very difficult
#{{ if (or (and (eq .chezmoi.os "linux") (eq .chezmoi.hostname "azusa")) (and (eq .chezmoi.os "windows") (eq .chezmoi.hostname "TanakaPC"))) }}
## NOTE: only be enabled at Home-azusa and Work-Windows
#[plugins."codecompanion.nvim"]
#git = "olimorris/codecompanion.nvim"
#cmds = [
#  "CodeCompanion",
#  "CodeCompanionActions",
#  "CodeCompanionChat",
#]
#{{ end }}

[plugins."dressing.nvim"]
#git = "stevearc/dressing.nvim"
version = "3.0.0"

[plugins."telescope.nvim"]
#git = "nvim-telescope/telescope.nvim"
version = "scm"

# NOTE: "hrsh7th/nvim-cmp" replacement
[plugins."magazine.nvim"]
name = "nvim-cmp"
#git = "iguanacucumber/magazine.nvim"
version = "0.2.1"

#------------------------------------------------------------------------------------
