[book]
authors = ["mimikun"]
language = "ja"
multilingual = false
src = "src"
title = "Commentary of dotfiles"

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
