[settings]
always_keep_download = false
always_keep_install = false
asdf_compat = true
disable_default_shorthands = false
disable_tools = []
experimental = false
jobs = 1
legacy_version_file = true
legacy_version_file_disable_tools = []
plugin_autoupdate_last_check_duration = 10080
raw = false
trusted_config_paths = []
verbose = false
yes = false
